# Generated by Django 5.0.6 on 2024-06-27 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=500)),
                ('sizes', models.DecimalField(decimal_places=2, max_digits=500)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('available', 'Available'), ('under_contract', 'Under Contract'), ('sold', 'Sold')], default='available', max_length=100)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], default='requested', max_length=80)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.property')),
            ],
        ),
    ]
